### ISSUE TITLE
How to use this project?

### ISSUE THREAD

**Issue by manisense** [Agri-Hub/Space2Ground#3]
How can we install this repo and use in locally? could you please provide some installation and documentation details?

**Comment by gchoumos** [comment]
Hello @elliotspark !

Have you tried to go through the details shared in the [README.md](https://github.com/Agri-Hub/Space2Ground/blob/main/README.md) file?

It includes:
- details for the dataset components
- instructions on how to download the dataset
- our [relevant publication (link)](https://arxiv.org/pdf/2205.07721.pdf)
- a Jupyter notebook with a pipeline that uses the dataset ([link](https://github.com/Agri-Hub/Space2Ground/blob/main/Space2Ground_use_case.ipynb))
- and we also share an extra jupyter notebook on how the ground-level component was cleaned ([link](https://github.com/Agri-Hub/Space2Ground/blob/main/streetLevel_patches.ipynb))

Let me know if you need something further to the above.

Thanks for your interest to our repo and work :)

Cheers,
George

**Comment by manisense** [comment]
Yes, it includes the data and the details but how to use it? where to put the data files? by using what commands we'll able to run the project? is it completely run into jupyter notebook?

**Comment by gchoumos** [comment]
Hello Elliot!

> it includes the data and the details but how to use it?
> by using what commands we'll able to run the project?

The ([Space2Ground_use_case](https://github.com/Agri-Hub/Space2Ground/blob/main/Space2Ground_use_case.ipynb)) Jupyter notebook is an example of a pipeline that showcases how this dataset can be used.

> where to put the data files?

The above Jupyter notebook in particular, expects the that the data are exist within the main repository directory (once you clone it) and inside a `data` folder as can be seen here:
<img width="736" alt="Screenshot 2023-03-31 at 3 42 31 PM" src="https://user-images.githubusercontent.com/15054198/229122960-c6ead908-9f87-4270-9580-2c5e158f8246.png">

But of course, feel free to edit it if you want to download the data at a different path.

> is it completely run into jupyter notebook?

Our example use case (grassland detection) is indeed running from within a Jupyter notebook, as you can see from the file I linked to. However, this is a dataset repository after all, and you are welcome to use it for your own purposes, build on top of it, or utilise it for other use cases as well.

Hope that helped.

Thanks,
George

**Comment by manisense** [comment]
okay thanks.
